name: CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup CMake caching
              uses: actions/cache@v4
              with:
                # Cache the CMake build directory
                path: build
                key: ${{ runner.os }}-cmake-${{ hashFiles('**/CMakeLists.txt') }}
                restore-keys: |
                    ${{ runner.os }}-cmake-

            - name: Install dependencies
              run: |
                sudo apt update
                sudo apt install -y cmake ocl-icd-opencl-dev opencl-headers

            - name: Discover and Build Applications
              run: |
                # Find each CMakeLists.txt file in the src directory
                for app_dir in src/*; do
                if [ -d "$app_dir" ] && [ -f "$app_dir/CMakeLists.txt" ]; then
                    echo "Building application in $app_dir"
                    mkdir -p build/$(basename "$app_dir")
                    cd build/$(basename "$app_dir")
                    cmake ../../"$app_dir"
                    cmake --build .
                    cd ../..
                fi
                done

            # - name: Build with CMake
            #   run: |
            #     mkdir -p build
            #     cd build
            #     cmake ..
            #     cmake --build .